# Generated by Django 2.2.4 on 2019-10-04 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDep', models.CharField(max_length=255, verbose_name='Nome do Departamento:')),
                ('numDep', models.CharField(max_length=255, verbose_name='Número do Departamento:')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura:')),
                ('numDoc', models.CharField(max_length=255, verbose_name='Número do documento:')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título:')),
                ('descricao', models.TextField(verbose_name='Descrição do Documento:')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=255, verbose_name='Matricula:')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome:')),
                ('cpf', models.CharField(max_length=255, verbose_name='CPF:')),
                ('pessoa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numProcesso', models.CharField(max_length=255, verbose_name='Número do Processo:')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura:')),
                ('dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_eleitoral.Departamento')),
                ('func', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_eleitoral.Funcionario')),
                ('interessada', models.ManyToManyField(related_name='Interessados', to='app_eleitoral.Pessoa')),
                ('investigada', models.ManyToManyField(related_name='Investigados', to='app_eleitoral.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoPrazo',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_eleitoral.Documento')),
                ('justificativa', models.TextField(verbose_name='Justificativa de Prazo:')),
                ('prazoAnterior', models.DateField(verbose_name='Prazo Anterior:')),
                ('prazoNovo', models.DateField(verbose_name='Novo Prazo:')),
            ],
            bases=('app_eleitoral.documento',),
        ),
        migrations.CreateModel(
            name='Portaria',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_eleitoral.Documento')),
                ('numPortaria', models.CharField(max_length=255, verbose_name='Número da Portaria de Instauração:')),
            ],
            bases=('app_eleitoral.documento',),
        ),
        migrations.CreateModel(
            name='Tramitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataChegada', models.DateField(verbose_name='Data de Chegada:')),
                ('dataSaida', models.DateField(verbose_name='Data de Saída:')),
                ('dataD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_eleitoral.Departamento')),
                ('origemD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Destino', to='app_eleitoral.Departamento')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_eleitoral.Processo')),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_eleitoral.Pessoa'),
        ),
        migrations.AddField(
            model_name='documento',
            name='func',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_eleitoral.Funcionario'),
        ),
        migrations.AddField(
            model_name='documento',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_eleitoral.Processo'),
        ),
        migrations.CreateModel(
            name='EnvioProcesso',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_eleitoral.Documento')),
                ('dataEnvio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio:')),
                ('dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_eleitoral.Departamento')),
            ],
            bases=('app_eleitoral.documento',),
        ),
    ]
